services:
  db:
    image: mariadb:10.4
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - pma
      - default

networks:
  pma:
    external: true

volumes:
  db_data:
